In [1]:
import pandas as pd
import sqlite3

ipl = pd.read_csv("IPL_ball_by_ball_updated.csv")
print("IPL CSV file imported successfully.")
print("Rows:", len(ipl))
print("Columns:", len(ipl.columns))

IPL CSV file imported successfully.
Rows: 243815
Columns: 22

In [2]:
display(ipl.head())

   match_id  season  ... other_wicket_type other_player_dismissed
0    335982    2008  ...               NaN                    NaN
1    335982    2008  ...               NaN                    NaN
2    335982    2008  ...               NaN                    NaN
3    335982    2008  ...               NaN                    NaN
4    335982    2008  ...               NaN                    NaN

[5 rows x 22 columns]

In [3]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243815 entries, 0 to 243814
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   match_id                243815 non-null  int64
 1   season                  243815 non-null  int64
 2   start_date              243815 non-null  object
 3   venue                   243815 non-null  object
 4   innings                 243815 non-null  int64
 5   ball                    243815 non-null  float64
 6   batting_team            243815 non-null  object
 7   bowling_team            243815 non-null  object
 8   striker                 243815 non-null  object
 9   non_striker             243815 non-null  object
 10  bowler                  243815 non-null  object
 11  runs_off_bat            243815 non-null  int64
 12  extras                  243815 non-null  int64
 13  wides                   7652 non-null    float64
 14  noballs                 1018 non-null    float64
 15  byes                    628 non-null     float64
 16  legbyes                 3778 non-null    float64
 17  penalty                 2 non-null       float64
 18  wicket_type             12067 non-null   object
 19  player_dismissed        12067 non-null   object
 20  other_wicket_type       0 non-null       float64
 21  other_player_dismissed  0 non-null       float64
dtypes: float64(8), int64(5), object(9)
memory usage: 40.9+ MB

In [4]:
display(ipl.describe(include="all").T)

                           count unique  ...        75%        max
match_id                243815.0    NaN  ...  1216507.0  1370353.0
season                  243815.0    NaN  ...     2020.0     2023.0
start_date                243815    762  ...        NaN        NaN
venue                     243815     56  ...        NaN        NaN
innings                 243815.0    NaN  ...        2.0        6.0
ball                    243815.0    NaN  ...       14.4       19.9
batting_team              243815     18  ...        NaN        NaN
bowling_team              243815     18  ...        NaN        NaN
striker                   243815    637  ...        NaN        NaN
non_striker               243815    626  ...        NaN        NaN
bowler                    243815    503  ...        NaN        NaN
runs_off_bat            243815.0    NaN  ...        1.0        6.0
extras                  243815.0    NaN  ...        0.0        7.0
wides                     7652.0    NaN  ...        1.0        5.0
noballs                   1018.0    NaN  ...        1.0        5.0
byes                       628.0    NaN  ...        4.0        4.0
legbyes                   3778.0    NaN  ...        1.0        5.0
penalty                      2.0    NaN  ...        5.0        5.0
wicket_type                12067     10  ...        NaN        NaN
player_dismissed           12067    602  ...        NaN        NaN
other_wicket_type            0.0    NaN  ...        NaN        NaN
other_player_dismissed       0.0    NaN  ...        NaN        NaN

[22 rows x 11 columns]

In [5]:
ipl_sample = ipl.head(20)
ipl_sample.to_excel("ipl_sample.xlsx", index=False)

ipl_excel = pd.read_excel("ipl_sample.xlsx")
print("Excel file imported successfully.")
display(ipl_excel.head())

Excel file imported successfully.

   match_id  season  ... other_wicket_type other_player_dismissed
0    335982    2008  ...               NaN                    NaN
1    335982    2008  ...               NaN                    NaN
2    335982    2008  ...               NaN                    NaN
3    335982    2008  ...               NaN                    NaN
4    335982    2008  ...               NaN                    NaN

[5 rows x 22 columns]

In [6]:
conn = sqlite3.connect("ipl_data.db")
ipl_sample.to_sql("ipl_deliveries", conn, if_exists="replace", index=False)

query = "SELECT * FROM ipl_deliveries LIMIT 5"
ipl_sql = pd.read_sql(query, conn)

print("SQL data imported successfully.")
display(ipl_sql)
conn.close()

SQL data imported successfully.

   match_id  season  ... other_wicket_type other_player_dismissed
0    335982    2008  ...              None                   None
1    335982    2008  ...              None                   None
2    335982    2008  ...              None                   None
3    335982    2008  ...              None                   None
4    335982    2008  ...              None                   None

[5 rows x 22 columns]

In [7]:
# Example web import syntax:
# url = "https://example.com/ipl_data.csv"
# web_data = pd.read_csv(url)
# display(web_data.head())

print("Web import syntax demonstrated using pd.read_csv(url).")

Web import syntax demonstrated using pd.read_csv(url).

In [8]:
ipl_sample.to_csv("ipl_export.csv", index=False)
print("IPL CSV file exported successfully.")
print("Exported rows:", len(ipl_sample))

IPL CSV file exported successfully.
Exported rows: 20

In [9]:
ipl_sample.to_excel("ipl_export.xlsx", index=False)
print("IPL Excel file exported successfully.")
print("Exported rows:", len(ipl_sample))

IPL Excel file exported successfully.
Exported rows: 20

In [10]:
ipl_sample.to_json("ipl_export.json", orient="records", indent=2)
print("IPL JSON file exported successfully.")
print("Exported records:", len(ipl_sample))

IPL JSON file exported successfully.
Exported records: 20

In [11]:
conn = sqlite3.connect("ipl_export.db")
ipl_sample.to_sql("ipl_data", conn, if_exists="replace", index=False)

count = pd.read_sql("SELECT COUNT(*) AS row_count FROM ipl_data", conn)
print("IPL data exported to SQLite successfully.")
display(count)
conn.close()

IPL data exported to SQLite successfully.

   row_count
0         20

In [12]:
print("Dataset shape:", ipl.shape)
print("Number of matches:", ipl["match_id"].nunique())
print("Seasons:", int(ipl["season"].min()), "to", int(ipl["season"].max()))
print("\nColumns:")
print(ipl.columns.tolist())

Dataset shape: (243815, 22)
Number of matches: 1024
Seasons: 2008 to 2023

Columns:
['match_id', 'season', 'start_date', 'venue', 'innings', 'ball', 'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes', 'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type', 'other_player_dismissed']